version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: admissions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nnamdi
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    health check:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admissions_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nnamdi
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8082"

volumes:
  db-data:
